### ISSUE TITLE
Problem rendering background

### ISSUE THREAD

**Issue by mariovillamizar** [flyerhq/react-native-keyboard-accessory-view#17]
Hey, thanks for this nice library!
I have a problem trying to render a background, since the background is covering the content. Do you have any idea on this?

**Comment by demchenkoalex** [comment]
Hi @mariovillamizar thanks for the kind words :) I will check this ASAP (probably this weekend). Can you please give an example of a background you are using? Is it ImageBackground or some kind of blur library?

**Comment by mariovillamizar** [comment]
Hey @demchenkoalex take a look of the screenshots:
![Simulator Screen Shot - iPhone 11 - 2021-04-08 at 12 30 51](https://user-images.githubusercontent.com/10704258/114071024-44020000-9866-11eb-9b0f-73279ef9b094.png)
![Simulator Screen Shot - iPhone 11 - 2021-04-08 at 12 31 02](https://user-images.githubusercontent.com/10704258/114071050-49f7e100-9866-11eb-9a7f-02ce74af694f.png)

This is my code:
```typescript
<KeyboardAccessoryView 
    contentContainerStyle={{overflow: 'hidden'}}
    renderScrollable={renderScrollable}
    renderBackground={renderBackground}
    useListenersOnAndroid
    spaceBetweenKeyboardAndAccessoryView={Platform.OS == 'android' ? 20 : 0}
    contentOffsetKeyboardOpened={Platform.OS == 'android' ? 20 : 40}
>
```

```typescript
const renderScrollable = (panHandlers: GestureResponderHandlers) => (
    <ScrollView ref={scrollView} keyboardDismissMode='interactive' {...panHandlers}>
        
        <View style={styles.recommendContainer}>
            <TextField
                value={screen.state.comment}
                containerStyle={styles.textFieldContainer}
                inputStyle={styles.textFieldInput}
                onChangeText={(text: string) => screen.setComment(text)}
                autoCapitalize={'sentences'}
                autoCorrect
                multiline
                maxLength={inputCharactersLimit}
                errorMessage={`${screen.state.comment?.length ?? 0}/${inputCharactersLimit}`}
                errorStyle={styles.textFieldCounter}
                scrollEnabled={false}
                onContentSizeChange={() => scrollView.current?.scrollToEnd()}
                //autoFocus
            />
        </View> 
    </ScrollView>
)

const renderBackground = () => (
    <View style={{backgroundColor: 'red', height: 400, width: 400}}></View>
)
```

The background view is the red box (just for test purposes). Let me know if you need some extra info.

**Comment by demchenkoalex** [comment]
I should probably emphasise this, but in the docs

` (e.g. <ImageBackground style={StyleSheet.absoluteFill} /> ). Remember about absolute positioning.`

background should be absolute positioned otherwise it will depend on a view you have in accessory, can you please try

```ts
<View style={StyleSheet.flatten([StyleSheet.absoluteFill, {backgroundColor: 'red', height: 400, width: 400}])}></View>
```

**Comment by demchenkoalex** [comment]
Hi @mariovillamizar were you able to fix this using absolute positioning?

**Comment by demchenkoalex** [comment]
Closing due no response, feel free to reopen if the issue is still there
