### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by kacgrzes** [flyerhq/react-native-keyboard-accessory-view#2]
First of all, great package! 🥇 Thanks for the contribution! I've left some small code review for you. Do whatever you'd like with it 😄 

- numbers such as: [1](https://github.com/flyerhq/react-native-keyboard-accessory--view/blob/master/src/__tests__/KeyboardAccessoryView.test.tsx#L35), [2](https://github.com/flyerhq/react-native-keyboard-accessory-view/blob/master/src/__tests__/KeyboardAccessoryView.test.tsx#L36), [3](https://github.com/flyerhq/react-native-keyboard-accessory-view/blob/master/src/__tests__/KeyboardAccessoryView.test.tsx#L45), [4](https://github.com/flyerhq/react-native-keyboard-accessory-view/blob/master/src/__tests__/KeyboardAccessoryView.test.tsx#L52) and [5](https://github.com/flyerhq/react-native-keyboard-accessory-view/blob/master/src/__tests__/KeyboardAccessoryView.test.tsx#L53) don't tell anything. Maybe you could put them in some more descriptive constants.
- Isn't minimal accepted duration in ms 1 frame so 1000 / 60 = 16.66? Referring to [this line](https://github.com/flyerhq/react-native-keyboard-accessory-view/blob/master/src/hooks/usePanResponder.tsx#L16)
- [Here](https://github.com/flyerhq/react-native-keyboard-accessory-view/blob/master/src/hooks/useComponentSize.tsx#L9) maybe you could simply just do:
```js
const { layout } = event.nativeEvent
setSize(layout)
```
- Maybe you could name [that type](https://github.com/flyerhq/react-native-keyboard-accessory-view/blob/master/src/hooks/useKeyboardDimensions.tsx#L32) instead of inlining it
- [move 10 to some const, for example, MIN_DURATION](https://github.com/flyerhq/react-native-keyboard-accessory-view/blob/master/src/hooks/useKeyboardDimensions.tsx#L52)
- [here] you could do something like this:
```js
Math.max(10, duration) // instead of this duration > 10 ? duration : 10
```
- in hooks tests, there are some low hanging values that could be moved to some constants.

**Comment by demchenkoalex** [comment]
Thanks for the review! :)

- Numbers check for the actual height based on the Dimensions and keyboard event mocks, so they will tell if something will be changed in `keyboardWillChangeFrame` event 
- Minimal accepted duration is taken from the React Native [source](https://github.com/facebook/react-native/blob/master/Libraries/Components/Keyboard/KeyboardAvoidingView.js#L106)
- Good suggestion with a `Math.max` :)
