### ISSUE TITLE
Scrollable cannot be set to fill entire height of container

### ISSUE THREAD

**Issue by andreialecu** [flyerhq/react-native-keyboard-accessory-view#24]
It appears that setting `flex: 1` on the `<ScrollView` passed to `renderScrollable` does not have any effect. This seems to be because of the container's style, I tracked it down to this part of the code:

https://github.com/flyerhq/react-native-keyboard-accessory-view/blob/93ce85552ec0f5d6b3c6ef05b20f6570db01f4f7/src/KeyboardAccessoryView.tsx#L75-L81

If I set `flex: 1` on the `Animated.View` everything works properly

Before:

<img width="442" alt="Screenshot 2021-05-23 at 19 59 11" src="https://user-images.githubusercontent.com/697707/119269641-59a66b80-bc01-11eb-9c3b-2f9cf71ce1f7.png">

After:

<img width="459" alt="Screenshot 2021-05-23 at 19 59 34" src="https://user-images.githubusercontent.com/697707/119269648-6925b480-bc01-11eb-9715-d4220b8c41e2.png">

**Comment by andreialecu** [comment]
This only occurs if the total height of the items being rendered are less than the screen height.

**Comment by demchenkoalex** [comment]
I guess I will need to add an additional optional style prop, not sure if `flex: 1` will work in every case

**Comment by andreialecu** [comment]
@demchenkoalex I originally wanted to implement it like in: https://github.com/flyerhq/react-native-keyboard-accessory-view/issues/7#issuecomment-691458629 which would've given more control over this. But the props in that example don't seem to exist on `KeyboardAccessoryView`. 

Neither `onContentBottomInsetUpdate` or `panResponderPositionY` seem to be available. Can you share any context regarding them?

Edit: Nevermind, by checking commit history I see they were removed and the API changed to use `renderScrollable`.

**Comment by demchenkoalex** [comment]
Released in [v2.2.0](https://github.com/flyerhq/react-native-keyboard-accessory-view/releases/tag/v2.2.0).
