### ISSUE TITLE
scroll over the keyboard with textinput

### ISSUE THREAD

**Issue by Larens94** [flyerhq/react-native-keyboard-accessory-view#29]
Hi, I need to know if it is possible to start the scroll like whatsapp does:
Now the scroll starts when you reach the keyboard, but I (having a textinput on it) would like it to start when you get to the edge of the textinput section.

I leave a video attached to make you understand.

https://user-images.githubusercontent.com/32598073/142661522-99137c8c-7b54-4f83-b275-99703ecc4b07.mp4

**Comment by demchenkoalex** [comment]
Sorry for the long response. Will see what I can do.

UPD: Spent a couple of hours on this and wasn't able to find a solution. I guess I forgot how this was written in the first place :(

**Comment by demchenkoalex** [comment]
Hi! This behaviour is now included in RN 0.68 and you don't need this library anymore. Refer to https://github.com/facebook/react-native/pull/31402. Thanks!
