### ISSUE TITLE
iOS negative keyboard height

### ISSUE THREAD

**Issue by piers-smartwyre** [flyerhq/react-native-keyboard-accessory-view#30]
Hi, first of all great project this is really useful! However I have stumbled across an issue on iOS.

https://user-images.githubusercontent.com/88309205/153897931-f4adb041-9d8c-4691-9d6c-bca15838f3e2.mov

It seems that the `updateKeyboardDimensions` function in node_modules/@flyerhq/react-native-keyboard-accessory-view/lib/hooks/useKeyboardDimensions.js is calculating a negative keyboard height of -174 when the keyboard closes which is different to it's original state where keyboard height is 0.

I've managed to solve this issue myself by using Math.max in this calculation, although I'm not sure if this is going to cause issues elsewhere!

**Comment by piers-smartwyre** [comment]
This could also be solved by adding the 'keyboardDidHide' listener to ios, resetting the value to 0 when it closes.

**Comment by demchenkoalex** [comment]
Hi! This behaviour is now included in RN 0.68 and you don't need this library anymore. Refer to https://github.com/facebook/react-native/pull/31402. Thanks!
