### ISSUE TITLE
got animate terrible in my project 

### ISSUE THREAD

**Issue by Yunnathai** [flyerhq/react-native-keyboard-accessory-view#35]
When I customize the expression panel, I like to switch between the panel and input. and the Input will flash his height like animate wrong, just like the video.

I hope the animation of input can be smooth.

https://user-images.githubusercontent.com/5283666/165905570-743bdab3-d3cb-4347-aac6-bc3c25d21a1b.mp4

**Comment by demchenkoalex** [comment]
Hi! This behaviour is now included in RN 0.68 and you don't need this library anymore. Refer to https://github.com/facebook/react-native/pull/31402. Thanks!
